#!/usr/bin/env python3
"""Deterministically build a scenario card HTML from its template by copying the
template and substituting ONLY the placeholder regions — the cp-then-edit
mechanism CLAUDE.md mandates, done in code so it is correct every run.

Why a script rather than hand-editing:

  1. **Escaping is a correctness bug, not a style preference.** The card's text
     fields are interpolated straight into markup. A scenario titled
     "CTA < 3 kelime olmalı mı?" or a KPI item mentioning "kargo & iade"
     silently produces broken or unexpected tags. abtest-card/SKILL.md already
     warns about this in prose; prose cannot enforce it. Here it is enforced:
     every text field goes through html.escape() before it reaches the template,
     and the bold label is applied AFTER escaping (the order SKILL.md specifies),
     so a label can never inject a tag.

  2. **The template's developer comment contains the same placeholders as the
     live skeleton.** `{{VARIANT_A_SCREEN}}` appears both inside the commented
     web/browser example and in the live phone skeleton. A naive string replace
     fills the comment too, shipping a half-substituted example block inside the
     delivered card. This tool strips the comment first, then substitutes.

  3. **Retyping ~180 lines of fixed CSS per card is the pipeline's largest time
     cost and its main drift risk.** After writing, this tool self-verifies that
     every fixed line of the template survived unchanged and refuses to emit a
     card that drifted.

Input is one JSON file describing the scenario:

  {
    "title":  "Kupon alanı katlanınca sepet dönüşümü artar mı?",
    "desc":   "Sepette açık duran kupon alanı ...",
    "device": "phone" | "web",              # default "phone"
    "url":    "site.com/sepet",             # web only, shown in the address bar
    "test_items": [
      "Kupon alanının katlanmış hâli",
      {"label": "Birincil KPI", "text": "sepet -> ödeme tamamlama"}
    ],
    "kpi_items":  [...],
    "dont_items": [...],
    "variant_a": "<div class=\"r-h\">Sipariş özeti</div>...",
    "variant_b": "<div class=\"r-h\">Sipariş özeti</div>..."
  }

Text fields (title, desc, and each item's label/text) are ESCAPED.
`variant_a` / `variant_b` are raw markup produced by the model for the mockup
region and are inserted verbatim — that region is generative by design, only its
surrounding skeleton is fixed.

Usage:
  build_card.py --template templates/scenario-card.html \
                --scenario scenario.json \
                --out abtest-card-kupon-alani.html

Exit: 0 = built and self-verified, 2 = usage error / drift detected.
"""
import argparse
import html
import json
import os
import re
import sys

# Placeholders the template exposes. Text ones are escaped; screen ones are raw.
TEXT_PLACEHOLDERS = ("{{TITLE}}", "{{DESC}}")
LIST_PLACEHOLDERS = {
    "{{TEST_ITEMS}}": "test_items",
    "{{KPI_ITEMS}}": "kpi_items",
    "{{DONT_ITEMS}}": "dont_items",
}
SCREEN_PLACEHOLDERS = {
    "{{VARIANT_A_SCREEN}}": "variant_a",
    "{{VARIANT_B_SCREEN}}": "variant_b",
}

# The developer comment in the template documents the web/browser skeleton and
# repeats the placeholders. It is guidance for whoever writes a card by hand and
# has no place in a delivered card.
COMMENT_RE = re.compile(r"[ \t]*<!--.*?-->\n?", re.DOTALL)

# Provenance, added by the builder rather than kept in the template — the line
# above strips every template comment, so a notice living there would be
# removed from exactly the artifact that travels. Cards get shared, forwarded
# and pasted into decks long after they leave the repo; this is the only thing
# that still says where one came from. Invisible on screen by design: it costs
# nothing in a client presentation, and removing it from generated output means
# editing the generator, not deleting a line from a file.
PROVENANCE = (
    "<!--\n"
    "  Generated by ab-test-playbook — https://github.com/ali-demirbas/ab-test-playbook\n"
    "  Copyright (c) 2026 Ali Demirbaş · MIT License\n"
    "  This card was produced by scripts/build_card.py from templates/scenario-card.html.\n"
    "-->\n"
)


def escape(text):
    """Escape a value for interpolation into markup. Non-strings are stringified."""
    return html.escape(str(text), quote=True)


def render_item(item):
    """One <li>. Accepts a plain string, or {"label": ..., "text": ...}.

    Escaping happens before the <b> wrapper is added, never after: a label of
    '<script>' must render as visible text, not as a tag. SKILL.md states this
    order in prose; this function is where it is actually guaranteed.
    """
    if isinstance(item, dict):
        label = item.get("label", "")
        text = item.get("text", "")
        if label and text:
            return "<li><b>%s</b> %s</li>" % (escape(label), escape(text))
        return "<li>%s</li>" % escape(label or text)
    return "<li>%s</li>" % escape(item)


def render_list(items, indent="        "):
    if not items:
        return ""
    return ("\n" + indent).join(render_item(i) for i in items)


def to_browser_skeleton(text, url):
    """Swap the live .phone skeleton for the .browser one (device_type: web).

    The template ships the phone skeleton live and the browser skeleton inside
    the developer comment. Rather than parse the comment, the browser markup is
    rebuilt here from the same class names, so a card can be produced for web
    without hand-copying anything out of a comment.
    """
    pattern = re.compile(
        r'<div class="phone">\s*'
        r'<div class="statusbar">.*?</div>\s*'
        r'<div class="screen">\s*(\{\{VARIANT_[AB]_SCREEN\}\})\s*</div>\s*'
        r'<div class="bottomnav">.*?</div>\s*'
        r"</div>",
        re.DOTALL,
    )

    def repl(m):
        return (
            '<div class="browser">\n'
            '        <div class="browser-bar">\n'
            '          <span class="browser-dot"></span>'
            '<span class="browser-dot"></span>'
            '<span class="browser-dot"></span>\n'
            '          <span class="browser-url">%s</span>\n'
            "        </div>\n"
            '        <div class="browser-screen">%s</div>\n'
            "      </div>" % (escape(url), m.group(1))
        )

    out, n = pattern.subn(repl, text)
    if n != 2:
        die("template does not expose two .phone skeletons to convert (found %d)" % n)
    return out


def strip_mockup_region(text):
    """Drop everything between the mockups block and the copy block.

    That region is the only part of the card whose *skeleton* legitimately
    differs between builds: device=web swaps the phone frame for a browser
    frame. Excluding it by boundary — rather than by guessing which lines
    mention 'phone' — keeps the drift check honest about everything else.
    """
    start = text.find('<div class="mockups">')
    end = text.find('<div class="copy">')
    if start == -1 or end == -1 or end < start:
        return text
    return text[:start] + text[end:]


def fixed_lines(template_text):
    """Lines of the template that must survive verbatim into the built card.

    Excluded: placeholder lines (swappable by design), developer comments
    (intentionally dropped), blank lines, and the mockup region (device-dependent).
    """
    stripped = strip_mockup_region(COMMENT_RE.sub("", template_text))
    out = []
    for line in stripped.splitlines():
        if "{{" in line:
            continue
        if not line.strip():
            continue
        out.append(line)
    return out


def build(template_text, scenario):
    device = scenario.get("device", "phone")
    if device not in ("phone", "web"):
        die("device must be 'phone' or 'web', got %r" % device)

    text = COMMENT_RE.sub("", template_text)

    if device == "web":
        text = to_browser_skeleton(text, scenario.get("url", ""))

    for ph in TEXT_PLACEHOLDERS:
        key = ph.strip("{}").lower()
        if ph in text:
            text = text.replace(ph, escape(scenario.get(key, "")))

    for ph, key in LIST_PLACEHOLDERS.items():
        if ph in text:
            text = text.replace(ph, render_list(scenario.get(key, [])))

    # Screens go in last and raw: this is the generative region.
    for ph, key in SCREEN_PLACEHOLDERS.items():
        if ph in text:
            text = text.replace(ph, str(scenario.get(key, "")))

    leftover = re.findall(r"\{\{[A-Z_]+\}\}", text)
    if leftover:
        die("template has placeholders this tool does not fill: %s" % ", ".join(sorted(set(leftover))))

    # After the strip, so it survives; before <html>, so it is the first thing
    # anyone reading the source sees. Case-insensitive on purpose: `<!doctype`
    # is equally valid HTML, and putting the notice above the doctype drops the
    # browser into quirks mode — a layout bug caused by a copyright line.
    if text.lstrip()[:9].upper() == "<!DOCTYPE":
        head, sep, rest = text.partition("\n")
        text = head + sep + PROVENANCE + rest
    else:
        text = PROVENANCE + text

    return text


def self_verify(built_text, template_text, device=None):
    """Refuse to emit a card that drifted from the template's fixed skeleton.

    `device` is accepted for call-site symmetry but no longer changes the check:
    the device-dependent region is excluded structurally by fixed_lines().
    """
    haystack = strip_mockup_region(built_text)
    missing = []
    for line in fixed_lines(template_text):
        if line not in haystack:
            missing.append(line.strip())
    if missing:
        preview = "\n  ".join(missing[:5])
        die(
            "drift: %d fixed template line(s) missing from the built card:\n  %s"
            % (len(missing), preview)
        )
    if "<script" in built_text.lower():
        die("cards are static HTML; refusing to emit a card containing <script>")


def die(msg):
    sys.stderr.write("build_card: %s\n" % msg)
    sys.exit(2)


def main(argv):
    ap = argparse.ArgumentParser(description="Build a scenario card from the template.")
    ap.add_argument("--template", required=True, help="path to templates/scenario-card.html")
    ap.add_argument("--scenario", required=True, help="JSON file describing the scenario")
    ap.add_argument("--out", required=True, help="path to write the card to")
    args = ap.parse_args(argv)

    for path in (args.template, args.scenario):
        if not os.path.isfile(path):
            die("no such file: %s" % path)

    with open(args.template, encoding="utf-8") as fh:
        template_text = fh.read()
    with open(args.scenario, encoding="utf-8") as fh:
        try:
            scenario = json.load(fh)
        except json.JSONDecodeError as exc:
            die("scenario is not valid JSON: %s" % exc)

    for required in ("title", "variant_a", "variant_b"):
        if not scenario.get(required):
            die("scenario is missing required field: %s" % required)

    built = build(template_text, scenario)
    self_verify(built, template_text, scenario.get("device", "phone"))

    out_dir = os.path.dirname(os.path.abspath(args.out))
    if out_dir and not os.path.isdir(out_dir):
        os.makedirs(out_dir, exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(built)

    print("built %s (%d bytes, device=%s)" % (args.out, len(built.encode("utf-8")), scenario.get("device", "phone")))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
